#!/usr/bin/env bash
# WHMCS MCP Server — Binary Installer
# https://daddar.io
#
# Usage:
#   bash setup.sh
#   curl -fsSL https://daddar.io/whmcs-mcp/install.sh | bash

set -euo pipefail

ARCH="$(uname -m)"
case "$ARCH" in
  x86_64)  BINARY_URL="https://daddar.io/download/whmcs-mcp-linux-x64" ;;
  aarch64) BINARY_URL="https://daddar.io/download/whmcs-mcp-linux-arm64" ;;
  *)       echo "Unsupported architecture: $ARCH"; exit 1 ;;
esac

INSTALL_DIR="/usr/local/bin"
BINARY="$INSTALL_DIR/whmcs-mcp"
ENV_FILE="/etc/whmcs-mcp.env"
SERVICE_FILE="/etc/systemd/system/whmcs-mcp.service"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[info]${RESET}  $*"; }
success() { echo -e "${GREEN}[ok]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[warn]${RESET}  $*"; }
die()     { echo -e "${RED}[error]${RESET} $*" >&2; exit 1; }
ask()     { echo -e "${BOLD}$*${RESET}"; }

echo ""
echo -e "${BOLD}${CYAN}╔════════════════════════════════════════╗${RESET}"
echo -e "${BOLD}${CYAN}║    WHMCS MCP Server — Binary Install   ║${RESET}"
echo -e "${BOLD}${CYAN}║           daddar.io                    ║${RESET}"
echo -e "${BOLD}${CYAN}╚════════════════════════════════════════╝${RESET}"
echo ""

[[ "$EUID" -eq 0 ]] || die "Run as root: sudo bash setup.sh"
command -v curl >/dev/null 2>&1 || die "curl is required."

# ── Download binary ───────────────────────────────────────────────────────────
info "Downloading whmcs-mcp binary ($ARCH)..."
curl -fsSL "$BINARY_URL" -o "$BINARY"
chmod +x "$BINARY"
success "Binary installed at $BINARY."

# ── Collect credentials ───────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}WHMCS API Credentials${RESET}"
echo "  (Find these in WHMCS: Setup → General Settings → Security → API Credentials)"
echo ""

ask "WHMCS URL (e.g. https://billing.example.com):"
read -r WHMCS_API_URL
[[ -n "$WHMCS_API_URL" ]] || die "WHMCS URL is required."

ask "WHMCS API Identifier:"
read -r WHMCS_IDENTIFIER
[[ -n "$WHMCS_IDENTIFIER" ]] || die "WHMCS API Identifier is required."

ask "WHMCS API Secret:"
read -rs WHMCS_SECRET; echo
[[ -n "$WHMCS_SECRET" ]] || die "WHMCS API Secret is required."

echo ""
echo -e "${BOLD}License${RESET}"
echo "  Purchase at https://daddar.io/store/ai-tools/whmcs-mcp. Leave blank for 14-day trial."
echo ""

ask "License Key (or press Enter for trial):"
read -r LICENSE_KEY

echo ""
echo -e "${BOLD}Network Setup${RESET}"
echo ""
ask "Server hostname or IP this will be reachable at (e.g. mcp.example.com):"
read -r WHMCS_MCP_HOST

# ── Write env file ────────────────────────────────────────────────────────────
info "Writing $ENV_FILE..."
cat > "$ENV_FILE" <<EOF
# WHMCS MCP Server — generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
WHMCS_API_URL=${WHMCS_API_URL}
WHMCS_IDENTIFIER=${WHMCS_IDENTIFIER}
WHMCS_SECRET=${WHMCS_SECRET}
LICENSE_KEY=${LICENSE_KEY}
MCP_TRANSPORT=http
MCP_HTTP_PORT=3100
MCP_HTTP_HOST=0.0.0.0
WHMCS_MCP_HOST=${WHMCS_MCP_HOST:-localhost}
MCP_AUTH_MODE=simple
MCP_REQUIRE_AUTH=true
MCP_DATA_DIR=/var/lib/whmcs-mcp
MCP_ENFORCE_HTTPS=false
MCP_TRUST_PROXY=true
MCP_RATE_LIMIT_ENABLED=true
MCP_METRICS_ENABLED=true
MCP_METRICS_PORT=9090
MCP_AUDIT_LOG_ENABLED=true
MCP_LOG_LEVEL=info
NODE_ENV=production
EOF
chmod 600 "$ENV_FILE"
success "$ENV_FILE written."

# ── Data directory ────────────────────────────────────────────────────────────
mkdir -p /var/lib/whmcs-mcp

# ── Systemd service ───────────────────────────────────────────────────────────
info "Installing systemd service..."
cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=WHMCS MCP Server
After=network.target

[Service]
EnvironmentFile=$ENV_FILE
ExecStart=$BINARY
Restart=always
RestartSec=5
User=nobody
Group=nogroup
WorkingDirectory=/var/lib/whmcs-mcp

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable whmcs-mcp
systemctl restart whmcs-mcp
success "Service started."

# ── Health check ──────────────────────────────────────────────────────────────
echo ""
info "Waiting for server to become healthy..."
ATTEMPTS=0
until curl -sf http://localhost:3100/health >/dev/null 2>&1 || [[ $ATTEMPTS -ge 15 ]]; do
  sleep 2; ATTEMPTS=$((ATTEMPTS + 1))
done

if curl -sf http://localhost:3100/health >/dev/null 2>&1; then
  success "Server is healthy."
else
  warn "Server did not respond in time. Check: journalctl -u whmcs-mcp -f"
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}╔════════════════════════════════════════╗${RESET}"
echo -e "${GREEN}${BOLD}║           Installation complete!       ║${RESET}"
echo -e "${GREEN}${BOLD}╚════════════════════════════════════════╝${RESET}"
echo ""
echo -e "  MCP endpoint:  ${BOLD}http://${WHMCS_MCP_HOST:-localhost}:3100/mcp${RESET}"
echo -e "  Health check:  ${BOLD}curl http://localhost:3100/health${RESET}"
echo -e "  Logs:          ${BOLD}journalctl -u whmcs-mcp -f${RESET}"
echo -e "  Config:        ${BOLD}$ENV_FILE${RESET}"
echo ""
echo -e "  Manage license: ${BOLD}https://daddar.io/clientarea/${RESET}"
echo ""
