#!/usr/bin/env bash
# WHMCS MCP Server — Interactive Installer
# https://daddar.io
#
# Usage:
#   bash setup.sh
#   curl -fsSL https://daddar.io/whmcs-mcp/install.sh | bash

set -euo pipefail

COMPOSE_FILE="docker-compose.marketplace.yml"
COMPOSE_URL="https://raw.githubusercontent.com/daddariotech/whmcs-mcp/main/docker-compose.marketplace.yml"
ENV_FILE=".env"

# ── Colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[info]${RESET}  $*"; }
success() { echo -e "${GREEN}[ok]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[warn]${RESET}  $*"; }
error()   { echo -e "${RED}[error]${RESET} $*" >&2; }
die()     { error "$*"; exit 1; }
ask()     { echo -e "${BOLD}$*${RESET}"; }

# ── Banner ────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${CYAN}╔════════════════════════════════════════╗${RESET}"
echo -e "${BOLD}${CYAN}║      WHMCS MCP Server — Installer      ║${RESET}"
echo -e "${BOLD}${CYAN}║           daddar.io                    ║${RESET}"
echo -e "${BOLD}${CYAN}╚════════════════════════════════════════╝${RESET}"
echo ""

# ── Prerequisites ─────────────────────────────────────────────────────────────
info "Checking prerequisites..."
command -v docker   >/dev/null 2>&1 || die "Docker is not installed. Install from https://docs.docker.com/get-docker/"
docker compose version >/dev/null 2>&1 || die "Docker Compose v2 is required. Update Docker Desktop or install the plugin."
command -v curl     >/dev/null 2>&1 || die "curl is required."
success "Docker $(docker --version | awk '{print $3}' | tr -d ,) found."

# ── Download compose file if not present ──────────────────────────────────────
if [[ ! -f "$COMPOSE_FILE" ]]; then
  info "Downloading $COMPOSE_FILE..."
  curl -fsSL "$COMPOSE_URL" -o "$COMPOSE_FILE" || die "Failed to download compose file."
  success "Downloaded $COMPOSE_FILE."
fi

# ── Collect credentials ───────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}WHMCS API Credentials${RESET}"
echo "  (Find these in WHMCS: Setup → General Settings → Security → API Credentials)"
echo ""

ask "WHMCS URL (e.g. https://billing.example.com):"
read -r WHMCS_API_URL
[[ -n "$WHMCS_API_URL" ]] || die "WHMCS URL is required."

ask "WHMCS API Identifier:"
read -r WHMCS_IDENTIFIER
[[ -n "$WHMCS_IDENTIFIER" ]] || die "WHMCS API Identifier is required."

ask "WHMCS API Secret:"
read -rs WHMCS_SECRET; echo
[[ -n "$WHMCS_SECRET" ]] || die "WHMCS API Secret is required."

ask "WHMCS Access Key (optional, press Enter to skip):"
read -r WHMCS_ACCESS_KEY

echo ""
echo -e "${BOLD}License${RESET}"
echo "  Purchase at https://daddar.io/store/ai-tools/whmcs-mcp. Leave blank to start a 14-day free trial."
echo ""

ask "License Key (or press Enter for trial):"
read -r LICENSE_KEY

# ── Reverse proxy detection ───────────────────────────────────────────────────
echo ""
echo -e "${BOLD}Network Setup${RESET}"
echo ""
ask "Are you running behind a reverse proxy (nginx, Caddy, Traefik)? [y/N]:"
read -r BEHIND_PROXY
BEHIND_PROXY="${BEHIND_PROXY,,}"

ENFORCE_HTTPS="false"
EXPOSE_PORT="true"
if [[ "$BEHIND_PROXY" == "y" || "$BEHIND_PROXY" == "yes" ]]; then
  EXPOSE_PORT="false"
  ENFORCE_HTTPS="true"
  info "Reverse proxy mode: port 3100 will NOT be exposed on host."
  info "Point your proxy to http://whmcs-mcp:3100 (internal container name)."
  echo ""
  ask "Public hostname for this server (e.g. mcp.example.com):"
  read -r WHMCS_MCP_HOST
else
  info "Direct mode: server will listen on port 3100."
  ask "Server hostname or IP (e.g. 192.168.1.100 or mcp.example.com):"
  read -r WHMCS_MCP_HOST
fi

# ── Auth mode ─────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}Authentication${RESET}"
echo "  simple = bearer tokens (recommended for most users)"
echo "  oauth  = full OAuth 2.0 PKCE (for multi-user / ChatGPT Actions)"
echo ""
ask "Auth mode [simple/oauth] (default: simple):"
read -r MCP_AUTH_MODE
MCP_AUTH_MODE="${MCP_AUTH_MODE:-simple}"
[[ "$MCP_AUTH_MODE" == "simple" || "$MCP_AUTH_MODE" == "oauth" ]] || MCP_AUTH_MODE="simple"

# ── Write .env ────────────────────────────────────────────────────────────────
info "Writing $ENV_FILE..."

cat > "$ENV_FILE" <<EOF
# WHMCS MCP Server — generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Do NOT commit this file to version control.

# WHMCS API
WHMCS_API_URL=${WHMCS_API_URL}
WHMCS_IDENTIFIER=${WHMCS_IDENTIFIER}
WHMCS_SECRET=${WHMCS_SECRET}
WHMCS_ACCESS_KEY=${WHMCS_ACCESS_KEY}

# License (blank = 14-day trial)
LICENSE_KEY=${LICENSE_KEY}
# MCP Server
MCP_TRANSPORT=http
MCP_HTTP_PORT=3100
MCP_HTTP_HOST=0.0.0.0
WHMCS_MCP_HOST=${WHMCS_MCP_HOST:-localhost}

# Authentication
MCP_AUTH_MODE=${MCP_AUTH_MODE}
MCP_REQUIRE_AUTH=true

# Security
MCP_ENFORCE_HTTPS=${ENFORCE_HTTPS}
MCP_TRUST_PROXY=true
MCP_ALLOWED_ORIGINS=*

# Rate limiting
MCP_RATE_LIMIT_ENABLED=true
MCP_RATE_LIMIT_WINDOW_MS=60000
MCP_RATE_LIMIT_PER_IP=120
MCP_RATE_LIMIT_PER_TOKEN=300

# Observability
MCP_METRICS_ENABLED=true
MCP_METRICS_PORT=9090
MCP_AUDIT_LOG_ENABLED=true
MCP_LOG_LEVEL=info

# Webhooks (optional — Pro/Agency tiers)
# WHMCS_WEBHOOK_SECRET=your-shared-secret-here

NODE_ENV=production
EOF

success ".env written."

# ── Patch compose file if reverse proxy mode ──────────────────────────────────
if [[ "$EXPOSE_PORT" == "false" ]]; then
  # Comment out the ports block so the container isn't exposed directly
  if command -v sed >/dev/null 2>&1; then
    sed -i 's/^    ports:$/    # ports: (removed — behind reverse proxy)/' "$COMPOSE_FILE" 2>/dev/null || true
    sed -i 's/^      - "3100:3100"$/      # - "3100:3100"/' "$COMPOSE_FILE" 2>/dev/null || true
  fi
fi

# ── Pull and start ─────────────────────────────────────────────────────────────
echo ""
info "Pulling latest image..."
docker compose -f "$COMPOSE_FILE" pull

info "Starting WHMCS MCP Server..."
docker compose -f "$COMPOSE_FILE" up -d

# ── Wait for health ────────────────────────────────────────────────────────────
echo ""
info "Waiting for server to become healthy..."
ATTEMPTS=0
MAX=15
if [[ "$EXPOSE_PORT" == "false" ]]; then
  HEALTH_CMD='docker exec whmcs-mcp curl -sf http://localhost:3100/health >/dev/null 2>&1'
else
  HEALTH_CMD='curl -sf http://localhost:3100/health >/dev/null 2>&1'
fi
until eval "$HEALTH_CMD" || [[ $ATTEMPTS -ge $MAX ]]; do
  sleep 2
  ATTEMPTS=$((ATTEMPTS + 1))
done

if eval "$HEALTH_CMD"; then
  success "Server is healthy."
else
  warn "Server did not respond in time. Check logs: docker logs whmcs-mcp"
fi

# ── Generate first token (simple mode only) ───────────────────────────────────
if [[ "$MCP_AUTH_MODE" == "simple" ]]; then
  echo ""
  info "Generating your first bearer token..."
  TOKEN_OUTPUT=$(docker exec whmcs-mcp node dist/scripts/auth-cli.js generate \
    --name "My AI" --scopes "mcp:read,mcp:write" 2>&1 || true)
  echo "$TOKEN_OUTPUT"
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}╔════════════════════════════════════════╗${RESET}"
echo -e "${GREEN}${BOLD}║           Installation complete!       ║${RESET}"
echo -e "${GREEN}${BOLD}╚════════════════════════════════════════╝${RESET}"
echo ""
echo -e "  MCP endpoint:  ${BOLD}http://${WHMCS_MCP_HOST:-localhost}:3100/mcp${RESET}"
echo -e "  Health check:  ${BOLD}http://localhost:3100/health${RESET}"
echo -e "  Logs:          ${BOLD}docker logs -f whmcs-mcp${RESET}"
echo ""
echo -e "  Add to Cursor (${BOLD}~/.cursor/mcp.json${RESET}):"
echo '  {'
echo '    "mcpServers": {'
echo '      "whmcs": {'
echo "        \"url\": \"http://${WHMCS_MCP_HOST:-localhost}:3100/mcp\","
echo '        "headers": { "Authorization": "Bearer <your-token>" }'
echo '      }'
echo '    }'
echo '  }'
echo ""
echo -e "  Manage license at: ${BOLD}https://daddar.io/clientarea/${RESET}"
echo ""
